name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'readme.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'readme.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:

    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
        
    - name: Test
      run: dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.SqliteTests" --configuration Release --framework net5.0
